FROM openjdk:11-jre-slim
LABEL maintainer="toandev020101@gmail.com"

# Set working directory
WORKDIR /allure

# Install curl, unzip, and required dependencies, download Allure, and clean up
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    && curl -o allure-2.33.0.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.33.0/allure-2.33.0.tgz \
    && echo "Download Complete" \
    && tar -zxvf allure-2.33.0.tgz -C /opt/ \
    && echo "Extraction Complete" \
    && ln -s /opt/allure-2.33.0/bin/allure /usr/bin/allure \
    && allure --version \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* allure-2.33.0.tgz

# Expose the port that Allure will serve on
EXPOSE 5252

# Run Allure serve command to display the results
CMD ["allure", "serve", "/allure-results", "--host", "0.0.0.0", "--port", "5252"]
