name:  fastapi-base

services:
  pcs_postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    container_name: pcs_postgres
    env_file:
      - ../.env.dev
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres_data:/data/postgres

  pcs_redis:
    image: redis:7.4.2
    restart: always
    container_name: pcs_redis
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pcs_opa:
    image: openpolicyagent/opa:1.2.0
    restart: always
    container_name: pcs_opa
    ports:
      - "8181:8181"
    volumes:
      - ../app/opa/rules/:/rules/:ro
    command: run --server --disable-telemetry --log-level debug --addr :8181 --watch /rules/
